Song.create(title: "Airbag", released: true, release_year: 1997, artist_name: "Radiohead", genre: "Rock")
Song.create(title: "Paranoid Android", released: true, release_year: 1997, artist_name: "Radiohead", genre: "Rock")
Song.create(title: "Subterranean Homesick Alien", released: true, release_year: 1997, artist_name: "Radiohead", genre: "Rock")
Song.create(title: "Exit Music(For a Film)", released: true, release_year: 1997, artist_name: "Radiohead", genre: "Rock")
Song.create(title: "Let Down", released: true, release_year: 1997, artist_name: "Radiohead", genre: "Rock")
Song.create(title: "Karma Police", released: true, release_year: 1997, artist_name: "Radiohead", genre: "Rock")
Song.create(title: "Climbing Up the Walls", released: true, release_year: 1997, artist_name: "Radiohead", genre: "Rock")
Song.create(title: "No Surprises", released: true, release_year: 1997, artist_name: "Radiohead", genre: "Rock")
Song.create(title: "Lucky", released: true, release_year: 1997, artist_name: "Radiohead", genre: "Rock")
Song.create(title: "The Tourist", released: true, release_year: 1997, artist_name: "Radiohead", genre: "Rock")
